### ISSUE TITLE
Can't install OpeniBoot and iDroid form bootlace

### ISSUE THREAD

**Issue by usami-muzugi** [iDroid-Project/Bootlace#2]
Iphone 3G,jailbreaked.got error msg "Error Unable to contact update server. Check your network connection." Pls help me...

**Comment by nickpack** [comment]
@usami-muzugi The project has been dead for years, the servers that hosted the files have long since been decommissioned - the only way you're going to be able to get iDroid now is by compiling everything from source and manually installing it.
